accounts/urls.py
from django.urls import path
from .views import user_login, user_logout, signup

urlpatterns = [
    path("login/", user_login, name="login"),
    path("logout/", user_logout, name="logout"),
    path("signup/", signup, name="signup"),
]

projects/urls.py
from django.urls import path
from .views import list_projects, show_project, create_project

urlpatterns = [
    path("", list_projects, name="list_projects"),
    path("<int:id>/", show_project, name="show_project"),
    path("create/", create_project, name="create_project"),
]

tasks/urls.py
from django.urls import path
from .views import create_task, show_my_tasks

app_name = "tasks"

urlpatterns = [
    path("create/", create_task, name="create_task"),
    path("mine/", show_my_tasks, name="show_my_tasks"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from projects.views import list_projects
from tasks.views import show_my_tasks

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("projects/", include("projects.urls")),
    path("tasks/", include("tasks.urls")),
    path("", list_projects, name="home"),
    path("show-my-tasks/", show_my_tasks, name="show_my_tasks"),
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    owner = models.ForeignKey(
        "auth.User",
        on_delete=models.CASCADE,
        related_name="projects",
        null=True,
    )
    members = models.ManyToManyField(
        User, related_name="member_projects", blank=True
    )

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from projects.models import Project


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        Project, related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        User,
        related_name="tasks_assigned",
        null=True,
        on_delete=models.CASCADE,
    )
    description = models.TextField(blank=True)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)


class UserCreationForm(forms.Form):
    username = forms.CharField(max_length=150)
    first_name = forms.CharField(max_length=150)
    last_name = forms.CharField(max_length=150)
    password = forms.CharField(
        max_length=150,
        widget=forms.PasswordInput,
    )
    password_confirmation = forms.CharField(
        max_length=150,
        widget=forms.PasswordInput,
    )

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirmation = cleaned_data.get("password_confirmation")

        if (
            password
            and password_confirmation
            and password != password_confirmation
        ):
            raise forms.ValidationError("The passwords do not match.")

        return cleaned_data

    def save(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        first_name = self.cleaned_data.get("first_name")
        last_name = self.cleaned_data.get("last_name")
        user = User.objects.create_user(
            username,
            password=password,
            first_name=first_name,
            last_name=last_name,
        )
        return user

projects/forms.py
from django import forms
from .models import Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ["name", "description", "owner"]
        widgets = {"owner": forms.HiddenInput()}

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if self.user:
            self.initial["owner"] = self.user.id

    def save(self, commit=True):
        instance = super().save(commit=False)
        if not instance.pk:
            instance.owner = self.user
        if commit:
            instance.save()
        return instance

tasks/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = ("is_completed",)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from accounts.forms import LoginForm, UserCreationForm
from django.contrib.auth.models import User


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            password_confirmation = form.cleaned_data["password2"]
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]

            if password == password_confirmation:
                user = User.objects.create_user(
                    username,
                    password=password,
                    first_name=first_name,
                    last_name=last_name,
                )
                login(request, user)
                return redirect("list_projects")
            else:
                form.add_error(
                    "password_confirmation", "The passwords do not match"
                )
    else:
        form = UserCreationForm()

    context = {"form": form}
    return render(request, "registration/signup.html", context)


def user_login(request):
    if request.method == "POST":
        form = LoginForm(request, request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data["username"],
                password=form.cleaned_data["password"],
            )
            if user is not None:
                login(request, user)
                return redirect("list_projects")
            else:
                form.add_error(None, "Invalid username or password.")
    else:
        form = LoginForm()
    context = {"form": form}
    return render(request, "registration/login.html", context)


def user_logout(request):
    logout(request)
    return redirect("login")

projects/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Project
from .forms import ProjectForm


@login_required
def list_projects(request):
    projects = Project.objects.filter(owner=request.user)
    return render(
        request, "projects/list_projects.html", {"projects": projects}
    )


@login_required
def create_project(request):
    if request.method == "POST":
        form = ProjectForm(request.POST, user=request.user)
        if form.is_valid():
            form.save()
            return redirect("list_projects")
    else:
        form = ProjectForm(user=request.user)
    return render(request, "projects/create_project.html", {"form": form})


def show_project(request, id):
    project = get_object_or_404(Project, id=id)
    context = {"project": project}
    return render(request, "projects/show_project.html", context)

tasks/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import TaskForm
from .models import Task


@login_required
def create_task(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.owner = request.user
            task.is_completed = False
            task.save()
            return redirect("show_projects")
    else:
        form = TaskForm()
    return render(request, "tasks/create_task.html", {"form": form})


@login_required
def show_my_tasks(request):
    tasks = Task.objects.filter(assignee=request.user)
    context = {"tasks": tasks}
    return render(request, "tasks/my_tasks.html", context)

projects/templates/projects/create_project.html
<!DOCTYPE html>
<html>
    <head>
        <title>Create Project</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if logged_in %}
                        <li>
                            <a href="show_my_tasks">My tasks</a>
                        </li>
                        <li>
                            <a href="list_projects">My projects</a>
                        </li>
                        <li>
                            <a href="logout">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="login">Login</a>
                        </li>
                        <li>
                            <a href="signup">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <div>
                <h1>Create a new project</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Create</button>
                </form>
            </div>
        </main>
    </body>
</html>

projects/templates/projects/list_projects.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>My Projects</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if logged_in %}
                        <li>
                            <a href="show_my_tasks">My tasks</a>
                        </li>
                        <li>
                            <a href="list_projects">My projects</a>
                        </li>
                        <li>
                            <a href="logout">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="login">Login</a>
                        </li>
                        <li>
                            <a href="signup">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <div>
                <h1>My Projects</h1>
                <p>
                    <a href="{% url 'create_project' %}">Create a new project</a>
                </p>
                {% if projects %}
                    <table>
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Number of tasks</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for project in projects %}
                                <tr>
                                    <td>
                                        <a href="{% url 'show_project' project.id %}">{{ project.name }}</a>
                                    </td>
                                    <td>{{ project.tasks.all|length }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p>You are not assigned to any projects</p>
                {% endif %}
            </div>
        </main>
    </body>
</html>

projects/templates/projects/show_project.html
<!DOCTYPE html>
<html>
    <head>
        <title>Project Detail</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if logged_in %}
                        <li>
                            <a href="show_my_tasks">My tasks</a>
                        </li>
                        <li>
                            <a href="list_projects">My projects</a>
                        </li>
                        <li>
                            <a href="logout">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="login">Login</a>
                        </li>
                        <li>
                            <a href="signup">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <div>
                <h1>{{ project.name }}</h1>
                <p>{{ project.description }}</p>
                <h2>Tasks</h2>
                {% if project.tasks.all %}
                    <table>
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Assignee</th>
                                <th>Start date</th>
                                <th>Due date</th>
                                <th>Is completed</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for task in project.tasks.all %}
                                <tr>
                                    <td>{{ task.name }}</td>
                                    <td>{{ task.assignee.username }}</td>
                                    <td>{{ task.start_date }}</td>
                                    <td>{{ task.due_date }}</td>
                                    <td>{{ task.is_completed|yesno:"yes,no" }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p>This project has no tasks</p>
                {% endif %}
            </div>
        </main>
    </body>
</html>

tasks/templates/tasks/create_task.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Create Task</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if logged_in %}
                        <li>
                            <a href="show_my_tasks">My tasks</a>
                        </li>
                        <li>
                            <a href="list_projects">My projects</a>
                        </li>
                        <li>
                            <a href="logout">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="login">Login</a>
                        </li>
                        <li>
                            <a href="signup">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <h1>Create Task</h1>
            <div>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Save</button>
                </form>
            </div>
        </main>
    </body>
</html>

tasks/templates/tasks/my_tasks.html
<!DOCTYPE html>
<html>
    <head>
        <title>My Tasks</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if logged_in %}
                        <li>
                            <a href="show_my_tasks">My tasks</a>
                        </li>
                        <li>
                            <a href="list_projects">My projects</a>
                        </li>
                        <li>
                            <a href="logout">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="login">Login</a>
                        </li>
                        <li>
                            <a href="signup">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <div>
                <h1>My Tasks</h1>
                {% if tasks %}
                    <table>
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Start date</th>
                                <th>Due date</th>
                                <th>Is completed</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for task in tasks %}
                                <tr>
                                    <td>{{ task.name }}</td>
                                    <td>{{ task.start_date }}</td>
                                    <td>{{ task.due_date }}</td>
                                    <td>{{ task.is_completed|yesno:"yes,no" }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p>You have no tasks</p>
                {% endif %}
            </div>
        </main>
    </body>
</html>

tasks/templates/tasks/project_detail.html
<!DOCTYPE html>
<html>
    <head>
        <title>Project Detail</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if logged_in %}
                        <li>
                            <a href="show_my_tasks">My tasks</a>
                        </li>
                        <li>
                            <a href="list_projects">My projects</a>
                        </li>
                        <li>
                            <a href="logout">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="login">Login</a>
                        </li>
                        <li>
                            <a href="signup">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <h1>{{ project.name }}</h1>
            <p>{{ project.description }}</p>
            <p>
                <a href="{% url 'tasks:create_task' %}">Create a new task</a>
            </p>
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Due Date</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for task in project.task_set.all %}
                        <tr>
                            <td>{{ task.name }}</td>
                            <td>{{ task.description }}</td>
                            <td>{{ task.due_date }}</td>
                            <td>
                                <a href="{% url 'tasks:update_task' task.id %}">Update</a> | <a href="{% url 'tasks:delete_task' task.id %}">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </main>
    </body>
</html>